[package]
name = "todo-mic-act"
version = "0.1.0"
authors = ["Guilherme Cintra (gcintra2) <gcintra2@na.xom.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"